const imageDescriptions: Record<string, string> = {
  "wedding-DSC00053.jpg": "Dwóch mężczyzn przygotowanych do ceremonii ślubnej",
  "wedding-DSC00073.jpg": "Ceremonia ślubna pod białą pergolą nad morzem",
  "wedding-DSC00107.jpg": "Dłonie pary podczas wymiany obrączek",
  "wedding-DSC00156.jpg": "Zakładanie obrączki podczas ceremonii ślubnej",
  "wedding-DSC00303.jpg": "Para młoda pochylona ku sobie podczas ceremonii",
  "wedding-DSC00400.jpg": "Para młoda trzymająca się za ręce po ceremonii",
  "wedding-DSC00755.jpg": "Wspólne zdjęcie gości weselnych na tle morza",
  "wedding-DSC01294.jpg": "Piramida kieliszków przygotowana na przyjęcie weselne",
  "wedding-DSC01302.jpg": "Pomarańczowe kieliszki sfotografowane na tle nieba",
  "wedding-DSC01303.jpg": "Piramida kieliszków z widokiem na morze",
  "wedding-DSC01306.jpg": "Wieża kieliszków z aperolem na tle morskiego widoku",
  "wedding-DSC01369.jpg": "Para młoda nalewająca napój do piramidy kieliszków",
  "wedding-DSC01446.jpg": "Panna młoda wznosząca kieliszek podczas przyjęcia",
  "wedding-DSC01759.jpg": "Weselna papeteria z motywem mapy na stole",
  "wedding-DSC01771.jpg": "Biała pergola ceremonii ślubnej z widokiem na morze",
  "wedding-DSC01786.jpg": "Pan młody obejmujący pannę młodą podczas sesji",
  "wedding-DSC01873.jpg": "Bliski portret pary młodej o zachodzie słońca",
  "wedding-DSC01893.jpg": "Para młoda pozująca nad morzem w wieczornym świetle",
  "wedding-DSC01972.jpg": "Pocałunek pary młodej pod welonem o zachodzie słońca",
  "wedding-DSC02023.jpg": "Para młoda na tle morza i ciemniejącego nieba",
  "wedding-DSC02096.jpg": "Detal sukni i biżuterii panny młodej",
  "wedding-DSC02128.jpg": "Czarno-biały portret panny młodej nad morzem",
  "wedding-DSC02162.jpg": "Czarno-biały portret pana młodego nad morzem",
  "wedding-DSC02172.jpg": "Dłoń pana młodego poprawiająca klapę marynarki",
  "wedding-DSC02203.jpg": "Para młoda stojąca razem na tle morza",
  "wedding-DSC02219.jpg": "Para młoda idąca brzegiem z widokiem na morze",
  "wedding-DSC02231.jpg": "Para młoda w ruchu podczas sesji nad morzem",
  "wedding-DSC02265.jpg": "Para młoda idąca po kamiennej ścieżce",
  "wedding-DSC02406.jpg": "Para młoda krojąca tort weselny",
  "wedding-DSC02428.jpg": "Para młoda degustująca tort przy weselnym stole",
  "wedding-DSC02430.jpg": "Uśmiechnięta para młoda przy torcie weselnym",
  "wedding-DSC02496.jpg": "Pan młody podnoszący pannę młodą podczas zabawy",
  "wedding-DSC02546.jpg": "Zbliżenie na buty pary młodej podczas tańca",
  "wedding-DSC09574.jpg": "Panna młoda siedząca podczas przygotowań do ślubu",
  "wedding-DSC09600.jpg": "Pan młody podczas przygotowań przed ceremonią",
  "wedding-DSC09614.jpg": "Obrączki ślubne w otwartych pudełkach",
  "wedding-DSC09634.jpg": "Papeteria ślubna ułożona na jasnym materiale",
  "wedding-DSC09672.jpg": "Zbliżenie obrączek w pudełkach z kwiatami",
  "wedding-DSC09689.jpg": "Ślubne detale i akcesoria na jasnym tle",
  "wedding-DSC09703.jpg": "Panna młoda podczas przygotowań przed niebieskimi drzwiami",
  "wedding-DSC09718.jpg": "Portret panny młodej przy niebieskich drzwiach",
  "wedding-DSC09898.jpg": "Nakryty stół weselny z widokiem na morze",
  "wedding-DSC09905.jpg": "Kwiaty i dekoracje stołu weselnego",
  "wedding-DSC09951.jpg": "Goście przy stołach podczas przyjęcia nad morzem",
  "unitedcrew-DSC07716.jpg": "Czarny Cadillac sfotografowany od przodu na zlocie",
  "unitedcrew-DSC07717.jpg": "Przedni bok czarnego Cadillaca z widocznym kołem",
  "unitedcrew-DSC07718.jpg": "Koło Cadillaca obok tablicy wystawowej",
  "unitedcrew-DSC07719.jpg": "Tylny zderzak Cadillaca z ozdobnymi wstążkami",
  "unitedcrew-DSC07720.jpg": "Detal tylnej części Cadillaca na zlocie",
  "unitedcrew-DSC07721.jpg": "Szary Dodge Charger pokazany od przodu",
  "unitedcrew-DSC07722.jpg": "Znaczek Dodge na przednim grillu samochodu",
  "unitedcrew-DSC07723.jpg": "Zbliżenie emblematu Charger na karoserii",
  "unitedcrew-DSC07724.jpg": "Przód Dodge Chargera pod festiwalowymi chorągiewkami",
  "unitedcrew-DSC07725.jpg": "Przednie koło i błotnik szarego Dodge Chargera",
  "unitedcrew-DSC07726.jpg": "Czarny Cadillac zaparkowany na trawie",
  "unitedcrew-DSC07727.jpg": "Czarny Cadillac pokazany z boku i od przodu",
  "unitedcrew-DSC07728.jpg": "Reflektor i przednie koło czarnego Cadillaca",
  "unitedcrew-DSC07729.jpg": "Koło Cadillaca ustawione na stojaku wystawowym",
  "unitedcrew-DSC07730.jpg": "Mycie przedniego koła samochodu na zlocie",
  "unitedcrew-DSC07731.jpg": "Strumień wody kierowany na koło samochodu",
  "unitedcrew-DSC07732.jpg": "Czerwony samochód z otwartą maską na zlocie",
  "unitedcrew-DSC07733.jpg": "Złote koło czerwonego samochodu",
  "unitedcrew-DSC07736.jpg": "Komora silnika samochodu z czerwonymi elementami",
  "unitedcrew-DSC07737.jpg": "Zielony samochód sportowy na terenie zlotu",
  "unitedcrew-DSC07738.jpg": "Zielony samochód sportowy pokazany od przodu",
  "unitedcrew-DSC07739.jpg": "Zbliżenie przedniego reflektora zielonego auta",
  "unitedcrew-DSC07740.jpg": "Złote koło zielonego samochodu sportowego"
};

export function describeGalleryImage(alt: string, source?: string): string {
  const filename = source?.match(/(?:wedding|unitedcrew)-DSC\d+\.jpg/i)?.[0];
  return (filename && imageDescriptions[filename]) || alt;
}
